# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
    - package-ecosystem: "github-actions"
      directory: "/"
      commit-message:
          prefix: "build(github-actions)"
      schedule:
          interval: "monthly"
      labels:
          - "dependabot"

    - package-ecosystem: "composer"
      directory: "/"
      commit-message:
          prefix: "build(dependencies)"
      schedule:
          interval: "monthly"
      labels:
          - "dependabot"
      ignore:
          - dependency-name: "*"
            update-types: [ "version-update:semver-major" ]
          - dependency-name: "php"
